name: sougou_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.2
  dio: ^5.7.0
  firebase_core: ^3.6.0
  firebase_in_app_messaging: ^0.8.0+7
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_inappwebview: ^6.1.1
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10
  flutter_widget_from_html: ^0.15.2
  google_mobile_ads: ^5.1.0
  http: ^1.2.2
  in_app_review: ^2.0.9
  internet_connection_checker: ^1.0.0+1
  lottie: ^3.1.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  provider: ^6.1.2
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  fl_chart: ^0.63.0
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  one_context: ^4.0.0
  bottom_navy_bar: ^6.0.0
  route_transitions: ^2.0.1
  toast: ^0.3.0
  shared_value: ^3.0.0
  intl: ^0.19.0
  syncfusion_flutter_charts: ^27.2.4
  validators: ^3.0.0
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  http_parser: ^4.0.2
  jwt_decoder: ^2.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  


dependency_overrides:
  # flutter_inappwebview_android:
  #   git:
  #     url: https://github.com/holzgeist/flutter_inappwebview
  #     path: flutter_inappwebview_android
  #     ref: d89b1d32638b49dfc58c4b7c84153be0c269d057
  win32: ^5.5.4
  archive: ^3.6.1
  webview_flutter_android: 3.16.1


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/logo.png
    - assets/icons/logo1.png
    - assets/logo/
    - assets/icon/
    - assets/img/
  fonts:
    - family: SegUI
      fonts:
        - asset: assets/fonts/segoeui.ttf
        - asset: assets/fonts/seguisb.ttf
          weight: 900
